name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    name: Testing build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Build MailHog
      run: docker build --tag mailhog
